import React, { useState, useEffect, useCallback } from 'react';
import { useAppContext } from '../store';
import { DPRReport, DPRStatus } from '../types/dpr';
import { DPRRegister } from '../components/dpr/DPRRegister';
import { DPREditor } from '../components/dpr/DPREditor';
import { DPRPreviewModal } from '../components/dpr/DPRPreviewModal';
import { DPRAuditModal } from '../components/dpr/DPRAuditModal';

export const DPR: React.FC = () => {
  const { user, projects = [] } = useAppContext();

  // Mode: 'register' | 'editor'
  const [viewMode, setViewMode] = useState<'register' | 'editor'>('register');
  const [reports, setReports] = useState<DPRReport[]>([]);
  const [loading, setLoading] = useState(false);
  const [activeReport, setActiveReport] = useState<DPRReport | null>(null);

  // Filters
  const [selectedProject, setSelectedProject] = useState('All');
  const [dateStart, setDateStart] = useState('');
  const [dateEnd, setDateEnd] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');

  // Modals
  const [previewDpr, setPreviewDpr] = useState<DPRReport | null>(null);
  const [auditTarget, setAuditTarget] = useState<{ dprId: string; reportNo: string } | null>(null);

  // Fetch reports from API
  const fetchReports = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (selectedProject && selectedProject !== 'All') params.append('projectId', selectedProject);
      if (dateStart) params.append('dateStart', dateStart);
      if (dateEnd) params.append('dateEnd', dateEnd);
      if (statusFilter && statusFilter !== 'All') params.append('status', statusFilter);

      const res = await fetch(`/api/dpr?${params.toString()}`);
      if (res.ok) {
        const data = await res.json();
        // Parse JSON sub-fields if returned as raw strings
        const parsed: DPRReport[] = data.map((d: any) => ({
          ...d,
          manpower: typeof d.manpowerJson === 'string' ? JSON.parse(d.manpowerJson || '[]') : (d.manpower || []),
          plantMachinery: typeof d.plantMachineryJson === 'string' ? JSON.parse(d.plantMachineryJson || '[]') : (d.plantMachinery || []),
          workExecuted: typeof d.workExecutedJson === 'string' ? JSON.parse(d.workExecutedJson || '[]') : (d.workExecuted || []),
          materialReceived: typeof d.materialReceivedJson === 'string' ? JSON.parse(d.materialReceivedJson || '[]') : (d.materialReceived || []),
          concrete: typeof d.concreteJson === 'string' ? JSON.parse(d.concreteJson || '[]') : (d.concrete || []),
          safety: typeof d.safetyJson === 'string' ? JSON.parse(d.safetyJson || '[]') : (d.safety || []),
          hindrances: typeof d.hindrancesJson === 'string' ? JSON.parse(d.hindrancesJson || '[]') : (d.hindrances || []),
          instructions: typeof d.instructionsJson === 'string' ? JSON.parse(d.instructionsJson || '[]') : (d.instructions || []),
          tomorrowPlan: typeof d.tomorrowPlanJson === 'string' ? JSON.parse(d.tomorrowPlanJson || '[]') : (d.tomorrowPlan || []),
          photos: typeof d.photosJson === 'string' ? JSON.parse(d.photosJson || '[]') : (d.photos || [])
        }));
        setReports(parsed);
      }
    } catch (err) {
      console.error('Error fetching DPR reports:', err);
    } finally {
      setLoading(false);
    }
  }, [selectedProject, dateStart, dateEnd, statusFilter]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  // Create New Report template
  const handleCreateNew = () => {
    const today = new Date().toISOString().substring(0, 10);
    const proj = projects[0];
    const initialReport: DPRReport = {
      id: '',
      reportNo: '', // Auto-generated by backend on save
      projectId: proj?.id || 'PRJ-MAIN',
      projectCode: (proj as any)?.projectCode || (proj as any)?.code || (proj?.id ? `PRJ-${proj.id.toUpperCase().substring(0, 6)}` : 'PRJ-01'),
      projectName: proj?.name || 'Main Construction Site',
      clientName: proj?.clientName || 'General Client',
      contractorName: 'SN ENTERPRISES',
      date: today,
      weather: 'Clear / Sunny (34°C)',
      workingHours: '08:00 AM - 06:00 PM (10 hrs)',
      status: 'Draft',
      preparedBy: user?.name || user?.username || 'Site Engineer',
      reviewedBy: 'Project Manager',
      approvedBy: 'Resident Engineer / Client Consultant',
      manpower: [
        { sNo: 1, trade: 'Masons', skilled: 4, semiSkilled: 2, unskilled: 4, total: 10, agency: 'SN Enterprises', remarks: 'Brickwork Block A' },
        { sNo: 2, trade: 'Bar Benders', skilled: 6, semiSkilled: 2, unskilled: 4, total: 12, agency: 'SN Enterprises', remarks: 'Column Reinforcement' },
        { sNo: 3, trade: 'Carpenters / Shuttering', skilled: 5, semiSkilled: 3, unskilled: 3, total: 11, agency: 'SN Enterprises', remarks: 'Slab Shuttering Grid 3-6' },
        { sNo: 4, trade: 'Electricians', skilled: 2, semiSkilled: 1, unskilled: 1, total: 4, agency: 'Sub-Agency PowerTech', remarks: 'Conduit laying' },
        { sNo: 5, trade: 'Helpers / Unskilled', skilled: 0, semiSkilled: 0, unskilled: 8, total: 8, agency: 'SN Enterprises', remarks: 'Material handling & site clearing' }
      ],
      plantMachinery: [
        { sNo: 1, equipment: 'Tower Crane 50m', nos: 1, hoursRun: 8, idleHours: 0, fuelLtr: 0, remarks: 'Operational - Lifting rebar & concrete', ownedOrHired: 'Owned' },
        { sNo: 2, equipment: 'Concrete Mixer (10/7 CFT)', nos: 2, hoursRun: 6.5, idleHours: 1.5, fuelLtr: 15, remarks: 'Operational for mortar mix', ownedOrHired: 'Owned' },
        { sNo: 3, equipment: 'Excavator (JCB 3DX)', nos: 1, hoursRun: 7, idleHours: 1, fuelLtr: 45, remarks: 'Backfilling work at foundation', ownedOrHired: 'Hired' },
        { sNo: 4, equipment: 'Needle Vibrators (Electric/Petrol)', nos: 4, hoursRun: 5, idleHours: 0, fuelLtr: 8, remarks: 'Operational during pour', ownedOrHired: 'Owned' }
      ],
      workExecuted: [
        { sNo: 1, location: 'Tower 1, 2nd Floor, Grid C4-E8', activity: 'RCC Slab Casting M25 grade concrete', unit: 'Cum', quantity: 45, cumulative: 310, drawingRef: 'SNE-STR-T1-L2-004 Rev.B', remarks: 'Completed with test cubes cast' },
        { sNo: 2, location: 'Tower 2, 1st Floor, Grid A1-B4', activity: 'AAC Block Masonry 200mm thick with mortar', unit: 'Sqm', quantity: 65, cumulative: 420, drawingRef: 'SNE-ARC-T2-L1-012', remarks: 'Curing initiated' },
        { sNo: 3, location: 'Basement 1, Retaining Wall North', activity: 'Waterproofing membrane application & protection', unit: 'Sqm', quantity: 80, cumulative: 540, drawingRef: 'SNE-SPE-WP-001', remarks: 'Joints sealed properly' }
      ],
      materialReceived: [
        { sNo: 1, material: 'OPC 53 Grade Cement (Ultratech)', unit: 'Bags', quantity: 400, challanNo: 'CH-98421', supplier: 'M/s Shree Balaji Traders', testCertificateReceived: 'Yes', remarks: 'Batch TC-2026-04 verified' },
        { sNo: 2, material: 'TMT Steel Fe550D (16mm & 20mm)', unit: 'MT', quantity: 18.5, challanNo: 'CH-87103', supplier: 'Tata Tiscon Steel Depo', testCertificateReceived: 'Yes', remarks: 'Sample taken for 3rd party testing' },
        { sNo: 3, material: 'Crushed Coarse Aggregate (20mm)', unit: 'CFT', quantity: 650, challanNo: 'DM-34190', supplier: 'Apex Stone Quarry', testCertificateReceived: 'NA', remarks: 'Visually inspected, silt content < 3%' }
      ],
      concrete: [
        { sNo: 1, memberLocation: 'Tower 1 - 2nd Floor Slab (Grid C-E)', grade: 'M25', volume: 45, slump: 110, cubesCast: 6, startFinishTime: '09:30 AM - 03:45 PM', remarks: 'Continuous pour, curing starts next day' }
      ],
      safety: [
        { id: 'saf-1', time: '08:00 AM', category: 'Toolbox Talk', observation: 'Morning Safety Pep-talk conducted on working at heights and harness use', actionTaken: 'All 45 workers attended and verified PPE', responsiblePerson: 'Safety Officer Rajesh', status: 'Closed' },
        { id: 'saf-2', time: '11:15 AM', category: 'PPE Compliance', observation: 'Two scaffolding helpers found without chin straps on helmets', actionTaken: 'Immediate correction done, straps replaced on spot', responsiblePerson: 'Supervisor Vikas', status: 'Rectified' }
      ],
      hindrances: [
        { id: 'hin-1', time: '02:00 PM', issue: 'Grid power disruption from local substation for 1.5 hours', location: 'Site wide', timeLost: '1.5 hrs', manpowerAffected: 15, actionTaken: 'Switched key loads to backup 125kVA DG set', personInformed: 'Site Incharge Mr. Gupta', timeInformed: '02:05 PM', status: 'Resolved', rfiRef: 'LOG-PWR-042' }
      ],
      instructions: [
        { id: 'ins-1', dateTime: `${today} 11:30 AM`, from: 'Mr. Arvind Sharma (Client Consultant PM)', instruction: 'Provide double coat damp-proof primer before blockwork plastering on external walls', location: 'Tower 2 External Facade', actionRequired: 'Issue instruction to plastering sub-contractor and procure specified primer', responsiblePerson: 'Site QA/QC Engineer', dueDate: today, status: 'In Progress' }
      ],
      tomorrowPlan: [
        { sNo: 1, location: 'Tower 1, 2nd Floor Slab', plannedActivity: 'Water curing & ponding bund preparation', unit: 'Sqm', plannedQuantity: 180, drawingRef: 'SNE-STR-T1-L2-004', remarks: 'Continuous wet curing required' },
        { sNo: 2, location: 'Tower 1, 3rd Floor Staging', plannedActivity: 'Scaffolding erection for columns Grid A1 to D5', unit: 'Nos', plannedQuantity: 14, drawingRef: 'SNE-STR-T1-L3-001', remarks: 'Inspection clearance by 04:00 PM' }
      ],
      photos: []
    };
    setActiveReport(initialReport);
    setViewMode('editor');
  };

  // Select an existing report to edit/view
  const handleSelectReport = (report: DPRReport) => {
    setActiveReport(report);
    setViewMode('editor');
  };

  // Save report (Create or Update)
  const handleSaveReport = async (data: DPRReport, bypassLock?: boolean, overrideReason?: string) => {
    try {
      const payload = {
        ...data,
        bypassLock: !!bypassLock,
        overrideReason: overrideReason || ''
      };

      let res;
      if (data.id) {
        // Update
        res = await fetch(`/api/dpr/${data.id}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            'x-user-username': user?.username || 'user'
          },
          body: JSON.stringify(payload)
        });
      } else {
        // Create
        res = await fetch('/api/dpr', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-user-username': user?.username || 'user'
          },
          body: JSON.stringify(payload)
        });
      }

      if (!res.ok) {
        const errJson = await res.json();
        throw new Error(errJson.error || 'Failed to save DPR');
      }

      const result = await res.json();
      alert(`Daily Progress Report ${result.reportNo || data.reportNo} saved successfully!`);
      await fetchReports();

      if (!data.id && result.id) {
        setActiveReport({ ...data, id: result.id, reportNo: result.reportNo });
      }
    } catch (err: any) {
      console.error(err);
      alert(`Error saving report: ${err.message}`);
      throw err;
    }
  };

  // Workflow status progression (Draft -> Submitted -> Reviewed -> Approved -> Locked)
  const handleWorkflowChange = async (targetStatus: DPRStatus | 'Unlocked', reason?: string) => {
    if (!activeReport || !activeReport.id) {
      alert("Please save the draft report first before advancing its workflow.");
      return;
    }

    try {
      const res = await fetch(`/api/dpr/${activeReport.id}/workflow`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-user-username': user?.username || 'user'
        },
        body: JSON.stringify({ targetStatus, reason })
      });

      if (!res.ok) {
        const errJson = await res.json();
        throw new Error(errJson.error || 'Workflow transition failed');
      }

      const result = await res.json();
      alert(`DPR ${result.reportNo} status updated to: ${result.status}`);
      setActiveReport(prev => prev ? { ...prev, status: result.status } : null);
      await fetchReports();
    } catch (err: any) {
      console.error(err);
      alert(`Error in workflow update: ${err.message}`);
      throw err;
    }
  };

  // Delete DPR (Draft only)
  const handleDeleteReport = async (id: string) => {
    if (!confirm("Are you sure you want to delete this draft Daily Progress Report?")) return;
    try {
      const res = await fetch(`/api/dpr/${id}`, {
        method: 'DELETE',
        headers: {
          'x-user-username': user?.username || 'user'
        }
      });
      if (!res.ok) {
        const errJson = await res.json();
        throw new Error(errJson.error || 'Delete failed');
      }
      alert("Report deleted successfully.");
      await fetchReports();
      if (activeReport?.id === id) {
        setActiveReport(null);
        setViewMode('register');
      }
    } catch (err: any) {
      alert(`Failed to delete DPR: ${err.message}`);
    }
  };

  return (
    <div className="flex flex-col h-full bg-[#f4f6f9]">
      {viewMode === 'register' ? (
        <DPRRegister
          reports={reports}
          projects={projects}
          loading={loading}
          selectedProject={selectedProject}
          setSelectedProject={setSelectedProject}
          dateStart={dateStart}
          setDateStart={setDateStart}
          dateEnd={dateEnd}
          setDateEnd={setDateEnd}
          statusFilter={statusFilter}
          setStatusFilter={setStatusFilter}
          searchQuery={searchQuery}
          setSearchQuery={setSearchQuery}
          onRefresh={fetchReports}
          onCreateNew={handleCreateNew}
          onSelectReport={handleSelectReport}
          onPreviewPDF={(r) => setPreviewDpr(r)}
          onOpenAudit={(dprId, reportNo) => setAuditTarget({ dprId, reportNo })}
          onDeleteReport={handleDeleteReport}
        />
      ) : activeReport ? (
        <DPREditor
          report={activeReport}
          projects={projects}
          currentUser={user}
          onSave={handleSaveReport}
          onWorkflowChange={handleWorkflowChange}
          onBack={() => setViewMode('register')}
          onPreviewPDF={() => setPreviewDpr(activeReport)}
          onOpenAudit={() => activeReport.id && setAuditTarget({ dprId: activeReport.id, reportNo: activeReport.reportNo })}
        />
      ) : null}

      {/* PDF Preview Modal */}
      <DPRPreviewModal
        isOpen={!!previewDpr}
        onClose={() => setPreviewDpr(null)}
        dpr={previewDpr}
      />

      {/* Audit Log Modal */}
      <DPRAuditModal
        isOpen={!!auditTarget}
        onClose={() => setAuditTarget(null)}
        dprId={auditTarget?.dprId || ''}
        reportNo={auditTarget?.reportNo || ''}
      />
    </div>
  );
};
