import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { FilteredAnalyticsData } from './analyticsData';
import { AnalyticsFilterState, formatINR } from './analyticsTypes';

export interface ExportReportHeaderMeta {
  companyName: string;
  reportName: string;
  projectName: string;
  clientName: string;
  financialYear: string;
  dateRange: string;
  generatedDate: string;
  generatedBy: string;
}

// 1. Export PDF
export const exportAnalyticsPDF = (
  analytics: FilteredAnalyticsData,
  filters: AnalyticsFilterState,
  meta: ExportReportHeaderMeta
) => {
  const doc = new jsPDF('landscape');

  // Enterprise Header Box
  doc.setFillColor(0, 47, 108); // Deep SAP Navy
  doc.rect(14, 12, 269, 22, 'F');

  // Company Name & Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('SN ENTERPRISES', 20, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('ERP SYSTEM &bull; BUSINESS INTELLIGENCE & ANALYTICS REPORT', 20, 29);

  // Right side report metadata
  doc.setFontSize(9);
  doc.text(`Report: ${meta.reportName}`, 200, 20);
  doc.text(`FY: ${meta.financialYear} | Date: ${meta.generatedDate}`, 200, 25);
  doc.text(`Generated By: ${meta.generatedBy}`, 200, 30);

  // Metadata sub-bar
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(9);
  let y = 40;
  doc.text(`Project: ${meta.projectName}`, 14, y);
  doc.text(`Client: ${meta.clientName}`, 100, y);
  doc.text(`Date Range: ${meta.dateRange || 'All Time'}`, 200, y);

  y += 6;

  // KPI Summary Table
  const kpiData = [
    [
      'Total Work Amount', formatINR(analytics.kpis.totalWorkAmount),
      'Total Billing Amount', formatINR(analytics.kpis.totalBillingAmount)
    ],
    [
      'Total Amount Received', formatINR(analytics.kpis.totalAmountReceived),
      'Total Outstanding', formatINR(analytics.kpis.outstanding)
    ],
    [
      'Total Site Expenses', formatINR(analytics.kpis.totalExpenses),
      'Worker Wages Paid', formatINR(analytics.kpis.totalWorkerPayments)
    ],
    [
      'Subcontractor Payouts', formatINR(analytics.kpis.totalSubcontractorPayments),
      'Active Projects / Workers', `${analytics.kpis.activeProjectsCount} Projects / ${analytics.kpis.activeWorkersCount} Workers`
    ]
  ];

  autoTable(doc, {
    startY: y,
    head: [['Financial KPI Metric', 'Value', 'Operational Metric', 'Value']],
    body: kpiData,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 86, 179],
      textColor: 255,
      fontSize: 9,
      fontStyle: 'bold'
    },
    bodyStyles: {
      fontSize: 8,
      cellPadding: 2
    },
    margin: { left: 14, right: 14 }
  });

  // @ts-ignore
  let finalY = doc.lastAutoTable.finalY + 8;

  // Monthly Financial Trend Table
  const monthlyRows = analytics.incomeVsExpense.map(row => [
    row.month,
    formatINR(row.clientReceived),
    formatINR(row.workerPayments),
    formatINR(row.subcontractorPayments),
    formatINR(row.expenses),
    formatINR(row.netCashflow)
  ]);

  if (monthlyRows.length > 0) {
    if (finalY > 160) {
      doc.addPage();
      finalY = 20;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 47, 108);
    doc.text('Monthly Financial & Cashflow Breakdown', 14, finalY);
    finalY += 4;

    autoTable(doc, {
      startY: finalY,
      head: [['Month', 'Client Received', 'Worker Payouts', 'Subcontractor Payouts', 'Site Expenses', 'Net Cashflow']],
      body: monthlyRows,
      theme: 'striped',
      headStyles: {
        fillColor: [70, 80, 95],
        textColor: 255,
        fontSize: 8,
        fontStyle: 'bold'
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 2
      },
      margin: { left: 14, right: 14 }
    });

    // @ts-ignore
    finalY = doc.lastAutoTable.finalY + 8;
  }

  // Client Outstanding Breakdown Table
  if (analytics.clientOutstanding.length > 0) {
    if (finalY > 160) {
      doc.addPage();
      finalY = 20;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 47, 108);
    doc.text('Client Collection & Outstanding Analysis', 14, finalY);
    finalY += 4;

    const clientRows = analytics.clientOutstanding.map(c => [
      c.clientName,
      formatINR(c.totalBilling),
      formatINR(c.amountReceived),
      formatINR(c.outstanding)
    ]);

    autoTable(doc, {
      startY: finalY,
      head: [['Client Name', 'Total Billed Amount', 'Amount Received', 'Outstanding Balance']],
      body: clientRows,
      theme: 'grid',
      headStyles: {
        fillColor: [0, 86, 179],
        textColor: 255,
        fontSize: 8,
        fontStyle: 'bold'
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 2
      },
      margin: { left: 14, right: 14 }
    });
  }

  // Page Numbers in Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `SN ENTERPRISES ERP &bull; Page ${i} of ${totalPages} &bull; Confidential Management Report`,
      14,
      200
    );
  }

  doc.save(`${meta.reportName.replace(/\s+/g, '_')}_${meta.financialYear}.pdf`);
};

// 2. Export Excel (Multi-Sheet: "Graph Summary" and "Source Data")
export const exportAnalyticsExcel = (
  analytics: FilteredAnalyticsData,
  meta: ExportReportHeaderMeta
) => {
  const wb = XLSX.utils.book_new();

  // Sheet 1: Graph & Financial Summary
  const summarySheetData: any[] = [
    ['SN ENTERPRISES - BUSINESS INTELLIGENCE & ANALYTICS REPORT'],
    ['Report Name', meta.reportName],
    ['Project', meta.projectName],
    ['Client', meta.clientName],
    ['Financial Year', meta.financialYear],
    ['Date Range', meta.dateRange || 'All'],
    ['Generated Date & Time', meta.generatedDate],
    ['Generated By', meta.generatedBy],
    [],
    ['KEY PERFORMANCE INDICATORS (KPIs)'],
    ['Metric', 'Amount (INR)'],
    ['Total Work Amount', analytics.kpis.totalWorkAmount],
    ['Total Billing Amount', analytics.kpis.totalBillingAmount],
    ['Total Client Amount Received', analytics.kpis.totalAmountReceived],
    ['Total Site Expenses', analytics.kpis.totalExpenses],
    ['Total Worker Wages Paid', analytics.kpis.totalWorkerPayments],
    ['Total Subcontractor Payouts', analytics.kpis.totalSubcontractorPayments],
    ['Net Outstanding Balance', analytics.kpis.outstanding],
    ['Active Projects Count', analytics.kpis.activeProjectsCount],
    ['Active Workers Count', analytics.kpis.activeWorkersCount],
    [],
    ['MONTHLY FINANCIAL TREND'],
    ['Month', 'Client Received', 'Worker Payouts', 'Subcontractor Payouts', 'Site Expenses', 'Net Cashflow'],
    ...analytics.incomeVsExpense.map(row => [
      row.month,
      row.clientReceived,
      row.workerPayments,
      row.subcontractorPayments,
      row.expenses,
      row.netCashflow
    ]),
    [],
    ['CLIENT OUTSTANDING POSITION'],
    ['Client Name', 'Total Billed', 'Amount Received', 'Outstanding Balance'],
    ...analytics.clientOutstanding.map(c => [
      c.clientName,
      c.totalBilling,
      c.amountReceived,
      c.outstanding
    ])
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summarySheetData);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Graph Summary');

  // Sheet 2: Source Data - Billings
  const billingsData = analytics.filteredRecords.billings.map(b => ({
    'Bill No': b.billNo,
    'Project ID': b.projectId,
    'Work Nature': b.workNature,
    'Certify Date': b.certifyDate,
    'Gross Amount': b.amount,
    'GST': b.gst || 0,
    'TDS': b.tds || 0,
    'Retention': b.retention || 0,
    'Debit Amount': b.debitAmount || 0,
    'Net Amount': (b.amount || 0) - (b.tds ?? 0) - (b.retention ?? 0) + (b.gst ?? 0) - (b.debitAmount ?? 0)
  }));
  const wsBillings = XLSX.utils.json_to_sheet(billingsData);
  XLSX.utils.book_append_sheet(wb, wsBillings, 'Source_Billings');

  // Sheet 3: Source Data - Client Payments
  const clientPaymentsData = analytics.filteredRecords.clientPayments.map(cp => ({
    'Payment ID': cp.id,
    'Project ID': cp.projectId,
    'Amount Received': cp.amountReceived,
    'Date': cp.date,
    'Remarks': cp.remarks || '',
    'Is Retention Payment': cp.isRetentionPayment ? 'Yes' : 'No'
  }));
  const wsPayments = XLSX.utils.json_to_sheet(clientPaymentsData);
  XLSX.utils.book_append_sheet(wb, wsPayments, 'Source_ClientPayments');

  // Sheet 4: Source Data - Expenses
  const expensesData = analytics.filteredRecords.expenses.map(e => ({
    'Date': e.date,
    'Description': e.description,
    'Project ID': e.projectId,
    'Kharchi': e.kharchi || 0,
    'Mess': e.mess || 0,
    'Advance': e.workerAdvance || 0,
    'Tiffin': e.tiffin || 0,
    'Travel': e.travel || 0,
    'Machinery / Material': e.machineryMaterial || 0,
    'Worker Payment': e.workerPayment || 0,
    'Stationery': e.stationery || 0,
    'Others': e.others || 0,
    'Total': (e.kharchi || 0) + (e.mess || 0) + (e.workerAdvance || 0) + (e.tiffin || 0) +
      (e.travel || 0) + (e.machineryMaterial || 0) + (e.workerPayment || 0) + (e.stationery || 0) + (e.others || 0)
  }));
  const wsExpenses = XLSX.utils.json_to_sheet(expensesData);
  XLSX.utils.book_append_sheet(wb, wsExpenses, 'Source_Expenses');

  // Sheet 5: Source Data - Subcontractors
  const subData = analytics.subcontractorBillingVsPayment.map(s => ({
    'Subcontractor Name': s.subcontractorName,
    'Total Bills': s.totalBills,
    'Total Payments': s.totalPayments,
    'Outstanding': s.outstanding
  }));
  const wsSub = XLSX.utils.json_to_sheet(subData);
  XLSX.utils.book_append_sheet(wb, wsSub, 'Source_Subcontractors');

  XLSX.writeFile(wb, `${meta.reportName.replace(/\s+/g, '_')}_${meta.financialYear}.xlsx`);
};

// 3. Print helper
export const printAnalyticsReport = () => {
  window.print();
};
